CREATE TABLE USER (
    U_ID MEDIUMINT NOT NULL AUTO_INCREMENT,     -- User ID Primary key
    U_HASH VARCHAR(128) NOT NULL UNIQUE, 	    -- Unique HASH for every user
    U_EXPENSES_DATE_RANGE VARCHAR(32) NOT NULL,
    U_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (U_ID)
);

CREATE TABLE PRODUCT (
    P_ID MEDIUMINT NOT NULL AUTO_INCREMENT,     
    U_ID MEDIUMINT,
    P_PRICE DECIMAL(6,2) NOT NULL, 	        
    P_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (P_ID),
    FOREIGN KEY (U_ID) REFERENCES USER(U_ID)
);

CREATE TABLE EXPENSE (
    E_ID MEDIUMINT NOT NULL AUTO_INCREMENT,     	                
    P_ID MEDIUMINT NOT NULL,
    ET_ID MEDIUMINT NOT NULL,
    PRIMARY KEY (E_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);

CREATE TABLE EXPENSETYPE (
    ET_ID MEDIUMINT NOT NULL AUTO_INCREMENT,     
    U_ID MEDIUMINT NOT NULL,	                
    ET_NAME VARCHAR(128) NOT NULL,
    ET_DESCRIPTION TEXT NOT NULL,
    ET_TYPE VARCHAR(64) NOT NULL,
    PRIMARY KEY (ET_ID)
);

CREATE TABLE GAS (
    G_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    P_ID MEDIUMINT NOT NULL,
    G_GALLONS DECIMAL(6,3) NOT NULL,
    P_PRICE DECIMAL(6,2), 	
    PRIMARY KEY (G_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);

CREATE TABLE MONTHLYEXPENSES (
    M_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_ID MEDIUMINT NOT NULL,
    M_MONTH VARCHAR(128) NOT NULL,
    M_YEAR INTEGER NOT NULL,
    M_DATE DATE NOT NULL,
    M_RENT DECIMAL(6,2) NOT NULL,
    M_ELECTRIC DECIMAL(6,2) NOT NULL,
    M_CELLPHONE DECIMAL(6,2) NOT NULL,
    M_TVINTERNET DECIMAL(6,2) NOT NULL,
    M_AUTODOC DECIMAL(6,2) NOT NULL,
    M_SCHOOLLOAN DECIMAL(6,2) NOT NULL,
    M_YEARLYACCOUNTS DECIMAL(6,2) NOT NULL,
    M_FOOD DECIMAL(6,2) NOT NULL,
    M_GAS DECIMAL(6,2) NOT NULL,
    M_GAS_GALLONS DECIMAL(6,2) NOT NULL,
    M_PERSONAL DECIMAL(6,2) NOT NULL,
    M_ENTERTAINMENT DECIMAL(6,2) NOT NULL,
    M_AUTO DECIMAL(6,2) NOT NULL,
    M_DINNER DECIMAL(6,2) NOT NULL,
    M_HOBBY DECIMAL(6,2) NOT NULL,
    M_PETS DECIMAL(6,2) NOT NULL,
    M_HOME DECIMAL(6,2) NOT NULL,
    M_TOTALCONST DECIMAL(6,2) NOT NULL,
    M_TOTALVAR DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (M_ID)
);
