CREATE TABLE USER (
    U_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_FNAME VARCHAR(64) NOT NULL,
    U_LNAME VARCHAR(64) NOT NULL,
    U_HASH VARCHAR(128) NOT NULL UNIQUE,
    U_USERNAME VARCHAR(64) NOT NULL,
    U_PASSWORD VARCHAR(64) NOT NULL,
    U_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (U_ID)
);