CREATE TABLE USER (
    U_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_HASH VARCHAR(128) NOT NULL UNIQUE,
    U_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (U_ID)
);

CREATE TABLE REVIEW (
    R_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    P_ID  MEDIUMINT,
    R_STAR SMALLINT NOT NULL,
    R_COMMENT TEXT,
    U_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (R_ID)
);

CREATE TABLE PRODUCT (
    P_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_ID MEDIUMINT,
    P_NAME VARCHAR(128) NOT NULL,
    P_SKU VARCHAR(64) NOT NULL,
    P_TYPE VARCHAR(32) NOT NULL,
    P_PRICE DECIMAL(6,2) NOT NULL,
    P_STATUS VARCHAR(64) NOT NULL,
    P_SDESC TEXT NOT NULL,
    P_LDESC TEXT NOT NULL,
    P_IMAGE VARCHAR(64) NOT NULL,
    P_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (P_ID),
    FOREIGN KEY (U_ID) REFERENCES USER(U_ID)
);

CREATE TABLE CART (
    C_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_ID MEDIUMINT NOT NULL,
    P_ID MEDIUMINT NOT NULL,
    C_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (C_ID)
);

CREATE TABLE ADDRESS (
    A_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_ID MEDIUMINT NOT NULL,
    O_ID MEDIUMINT NOT NULL,
    A_NAME VARCHAR(64) NOT NULL,
    A_PNUMBER VARCHAR(64) NOT NULL,
    A_ADDRESS1 VARCHAR(64) NOT NULL,
    A_ADDRESS2 VARCHAR(64),
    A_CITY VARCHAR(32) NOT NULL,
    A_STATE CHAR(2) NOT NULL,
    A_ZIP VARCHAR(16) NOT NULL,
    A_EMAIL VARCHAR(64) NOT NULL,
    A_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (A_ID),
    FOREIGN KEY (U_ID) REFERENCES USER(U_ID)
);

CREATE TABLE SHIPPING (
    S_ID MEDIUMINT NOT NULL,
    S_TYPE VARCHAR(32) NOT NULL,
    S_COST DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (S_ID)
);

CREATE TABLE ORDERS (
    O_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    U_ID MEDIUMINT NOT NULL,
    O_QTY MEDIUMINT NOT NULL,
    O_SHIPPING VARCHAR(16) NOT NULL,
    O_AMOUNT DECIMAL(6,2) NOT NULL,
    O_TOTAL_P DECIMAL(6,2) NOT NULL,
    O_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (O_ID)
);

CREATE TABLE PURCHASED_PRODUCT (
    O_ID MEDIUMINT NOT NULL DEFAULT 0,
    U_ID MEDIUMINT NOT NULL,
    P_ID MEDIUMINT NOT NULL,
    PR_TIMESTAMP TIMESTAMP
);
